name: NewDayWarp
version: '${version}'
main: org.lumenk.newdaywarp.NewDayWarp
api-version: 1.18
authors: [ SeHyeonBak ]
depend : [WorldGuardEvents]
commands:
  warpdata:
    permission: newday.engineer